#!/bin/bash
export DYLD_LIBRARY_PATH=/Users/scott/src/ACE_wrappers/ace
rm -f pond.log
rm -f tock.log
./duckmo --prequit
/usr/local/bin/comdraw -geometry 1400x1000 >&comdraw.log &
sleep 2
./duckmo >&duckmo.log &
sleep 2
testit DuckPondC -chansz 1 >& log

